- name: Replace virtualbox inserted nameserver with Google's
  copy:
    src: "{{ VAGRANT_RESOLV_CONF }}"
    dest: /etc/resolv.conf

- name: Update hosts file
  lineinfile:
    dest: /etc/hosts
    line: "{{ item }}"
  with_items: "{{ ETC_HOSTS }}"

- name: Enable SSH password authentication
  replace:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.Find }}"
    replace: "{{ item.Replace }}"
  with_items:
      - { Find: 'PasswordAuthentication no', Replace: 'PasswordAuthentication yes' }
      - { Find: '#PermitEmptyPasswords no', Replace: 'PermitRootLogin yes' }

- name: Restart OpenSSH daemon
  service:
    name: sshd
    state: restarted

- name: Set root password
  remote_user: root
  user:
    name: root
    password: "{{ VAGRANT_ROOT_PASS }}"
    update_password: always

- name: Disable SELinux
  selinux:
    state: disabled
  when: ansible_os_family == "RedHat"

- name: Set locale
  lineinfile:
    path: /etc/environment
    line: "{{ item }}"
    state: present
  with_items: "{{ CENTOS_LOCALES }}"
  when: ansible_os_family == "RedHat"

- name: Start and enable NFS service
  service:
    name: "{{ NFS_SERVICE }}"
    state: started
    enabled: true
  when:
    - ansible_os_family == "RedHat"
    - hostvars[inventory_hostname].ansible_hostname == "storage"
